[package]
name = "tanguieta"
version = "0.1.0"
authors = ["José G. Quenum <josum@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
